[package]
name = "wasm_scrollbar"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.73"
web-sys = { version = "0.3", features = ["Document", "Window", "Element", "HtmlElement", "MouseEvent", "Node", "Event", "EventTarget"] }
js-sys = "0.3.50"

